# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-07-01 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Reviewed_at',
            new_name='Created_at',
        ),
    ]
